---
- name: Configuración de IIS en Windows
  hosts: windows
  tasks:
    - name: Asegurarse de que IIS esté instalado
      win_feature:
        name: Web-Server
        state: present

    - name: Asegurarse de que el servicio de IIS esté iniciado
      win_service:
        name: W3SVC
        start_mode: auto
        state: started

    - name: Permitir tráfico HTTP a través del firewall
      win_firewall_rule:
        name: 'IIS HTTP'
        enable: yes
        direction: in
        action: allow
        protocol: TCP
        localport: 80

    - name: Crear una página de prueba para IIS
      win_shell: |
        <!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tienda Oficial de Playeras Tigres UANL</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #F2F2F2;
        }

        header {
            background-color: #F9A800; /* Color del equipo */
            color: white;
            padding: 20px;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }

        nav ul {
            list-style-type: none;
            padding: 0;
        }

        nav ul li {
            display: inline;
            margin: 0 15px;
        }

        nav ul li a {
            color: white;
            text-decoration: none;
        }

        section {
            padding: 20px;
            margin: 10px 0;
        }

        .product-container {
            display: flex;
            flex-wrap: wrap; /* Permite que los elementos se envuelvan */
            justify-content: space-between; /* Espacio uniforme entre productos */
        }

        .product {
            border: 1px solid #F9A800;
            padding: 15px;
            margin: 10px;
            text-align: center;
            width: calc(50% - 40px); /* Dos productos por fila */
            height: 350px; /* Altura fija para todos los productos */
            box-sizing: border-box; /* Incluye padding y border en el cálculo de ancho y alto */
        }

        .product img {
            width: 100%; /* Imágenes responsivas */
            height: auto;
            max-height: 200px; /* Máxima altura de la imagen para uniformidad */
        }

        footer {
            background-color: #333;
            color: white;
            text-align: center;
            padding: 10px;
            position: relative;
            bottom: 0;
            width: 100%;
        }

        /* Estilos para el logo */
        .logo {
            display: flex;
            align-items: center;
        }

        .logo img {
            width: 50px; /* Ajusta el tamaño del logo aquí */
            height: auto; /* Mantiene la proporción de la imagen */
            margin-right: 10px; /* Espacio entre el logo y el título */
        }

        .logo h1 {
            font-size: 24px; /* Tamaño del texto del título */
            margin: 0; /* Elimina el margen del h1 */
        }
    </style>
</head>
<body>
    <header>
        <div class="logo">
            <img src="https://th.bing.com/th/id/OIP.pOz628UOZ8AipzRiivr1NQHaLK?rs=1&pid=ImgDetMain" alt="Logo Tigres UANL">
            <h1>Tienda Tigres UANL</h1>
        </div>
        <nav>
            <ul>
                <li><a href="#home">Inicio</a></li>
                <li><a href="#about">Acerca de</a></li>
                <li><a href="#shop">Tienda</a></li>
                <li><a href="#contact">Contacto</a></li>
            </ul>
        </nav>
    </header>

    <section id="home">
        <h2>Bienvenido a la Tienda Oficial de Playeras Tigres UANL</h2>
        <p>Compra tus playeras favoritas y muestra tu apoyo a Tigres.</p>
    </section>

    <section id="about">
        <h2>Acerca de Nosotros</h2>
        <p>En nuestra tienda, ofrecemos una variedad de playeras oficiales de Tigres UANL para que los aficionados puedan lucir los colores de su equipo.</p>
    </section>

    <section id="shop">
        <h2>Nuestra Colección</h2>
        <div class="product-container">
            <div class="product">
                <img src="https://th.bing.com/th/id/OIP.sP7o35oAdJ7BnE9DGXI5vAHaHa?rs=1&pid=ImgDetMain" alt="Playera Tigres 2024">
                <h3>Playera Tigres 2024</h3>
                <p>Precio: $800 MXN</p>
                <button>Añadir al Carrito</button>
            </div>
            <div class="product">
                <img src="https://d16el6lbhkecqm.cloudfront.net/cache/catalog/HS2032_FR_eCom-600x600.jpg" alt="Playera Tigres Retro">
                <h3>Playera Tigres Retro</h3>
                <p>Precio: $700 MXN</p>
                <button>Añadir al Carrito</button>
            </div>
            <div class="product">
                <img src="https://www.soccerbible.com/media/154433/tigres-10-min.jpg" alt="Playera Tigres Edición Especial">
                <h3>Playera Tigres Edición Especial</h3>
                <p>Precio: $900 MXN</p>
                <button>Añadir al Carrito</button>
            </div>
            <div class="product">
                <img src="https://th.bing.com/th/id/OIP.115ThvN-k4Ahs-mcJl11XgHaHa?rs=1&pid=ImgDetMain" alt="Playera Tigres Edición Especial">
                <h3>Playera Tigres Edición Especial2</h3>
                <p>Precio: $900 MXN</p>
                <button>Añadir al Carrito</button>
            </div>
        </div>
    </section>

    <section id="contact">
        <h2>Contacto</h2>
        <p>Si tienes alguna pregunta, no dudes en <a href="mailto:info@tigresuanl.com">enviarnos un correo electrónico</a>.</p>
    </section>

    <footer>
        <p>&copy; 2024 Tienda Tigres UANL. Todos los derechos reservados.</p>
    </footer>
</body>
</html>
